mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
]
urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'
urlpatterns = [
    path('', index, name='home'),
    path('register/', register, name='register'),
    path('dashboard/', dashboard, name='dashboard'),
    path('user_logout/', user_logout, name='logout'),
    path('user_delete/<pkid>/', user_delete, name='user_delete'),
    path('users_list/', users_view, name='users_list'),
    path('user_detail_view/<pkid>', user_detail_view, name='users_detail_view'),
    path('user_update_view/<pkid>', user_update_view, name='users_update_view'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render,redirect,get_list_or_404
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

# Create your views here.

def index(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        login(request,user)
        return redirect('users:dashboard')
    else:
        return render(request, 'users/login.html')


def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            form = UserCreationForm()
            messages.success(request, "User has been Created!")
        else:
            messages.error(request, "Failed to create the User! Something went wrong!")    
    context = {
        'form': form
    }
    return render(request, 'users/register.html', context=context)
    

@login_required
def dashboard(request):
    user = request.user
    if user.is_superuser == True:
        context = {
            'title': "Admin::Dashboard"
        }
        return render(request, 'users/admin/dashboard.html', context=context)
    else:
        context = {
            'username': user.username,
            'title': "User::Dashboard"
        }
        return render(request, 'users/user/dashboard.html', context=context)

@login_required
def user_logout(request):
    logout(request)
    return redirect('users:home')


@login_required
def user_delete(request, pkid):
    user = User.objects.get(id=pkid).delete()
    messages.success(request,  ' Deleted!')
    return redirect("users:dashboard")

@login_required    
def users_view(request):
    user = get_list_or_404(User)
    context =  {
        'users': user,
    }
    return render(request, 'users/admin/users_page.html', context=context)

@login_required
def user_detail_view(request, pkid):
    user = User.objects.get(id=pkid)
    context = {
        'first_name': user.first_name,
        'last_name': user.last_name,
        'username': user.username,
        'last_login': user.last_login,
        'date_joined': user.date_joined,
    }
    return render(request, 'users/admin/detail_view.html', context=context)


def user_update_view(request, pkid):
    user = User.objects.get(id=pkid)
    form = UserChangeForm(instance=user)
    if request.method == "POST":
        form = UserChangeForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "User data has been updated!!")
        else:
            form = UserChangeForm(instance=user)
            messages.error(request, "Something went wrong!!!")
    context = {
        'form': form
    }
    return render(request, 'users/admin/user_change_page.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "./css/main.css" %}">
    <title>
        {% if title %}
            {{title}}
        Blog::APP
        {% endif %}
    </title>
</head>
<body>
    {% block content %}{% endblock content %}
<script src="{% static "./js/main.js" %}"></script>
</body>
</html>

templates/includes/admin/nav.html
<nav class="sidebar">
    <ul class="nav-menu">
        <li class="nav-item">
            <a href="#" class="nav-link">Home</a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link">Sessions</a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link">Settings</a>
        </li>
        <li class="nav-item">
            <a href="{% url "users:users_list" %}" class="nav-link">Users</a>
        </li>
        <li class="nav-item">
            <a href="{% url "users:logout" %}" class="nav-link">Logout</a>
        </li>
    </ul>
</nav>

templates/users/admin/dashboard.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
    {% include "includes/admin/nav.html" %}
    <div class="container">
        
    </div>
</div>
{% endblock content %}

templates/users/admin/detail_view.html
{% extends "base.html" %}
{% block content %}
    <p>First Name: {{first_name}}</p>
    <p>Last Name: {{last_name}}</p>
    <p>Username: {{username}}</p>
    <p>Date Joined: {{date_joined}}</p>
{% endblock content %}

templates/users/admin/user_change_page.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger">{{ message }}</div>
            {% endfor %}
        {% endif %}
    </div> 
    <div class="row">
        <h3>Edit your details</h3> 
    </div>
    <div clas="row">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div clas="row">
                    <div class="col-4">
                        {{ form.as_div }}
                    </div>
                    <div class="col-4">
                        <input type="submit" class="button" value="Update" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/users/admin/users_page.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger">{{ message }}</div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="container">
        <div class="row">
            <table>
                <tr>
                    <th>Id</th>
                    <th>username</th>
                    <th>Actions</th>
                </tr>
            {% for user in users %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{user}}</td>
                <td>
                    <a href="{% url "users:users_update_view" user.id%}">Edit</a>
                    <a href="{% url "users:user_delete" user.id%}">Delete</a>
                    <a href="{% url "users:users_detail_view" user.id %}">View</a>
                </td>
            </tr>
            {% endfor %}
            </table>
        </div>
    </div>
{% endblock content %}

templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <img src="{% static "./img/banner.png" %}" class="image_thumbnail"/>
            </div>
            <div class="col-md-4">
                <form  method="post" class="user_login" id="user_login">
                    {% csrf_token %}
                    <div class="col-4">
                        <label for="username" class="title">
                            Username:
                        </label>
                        <input type="text" name="username" class="username" id="username">
                    </div>
                    <div class="col-4">
                        <label for="password" class="title">
                            Password:
                        </label>
                        <input type="password" name="password" class="password" id="password">
                    </div>
                    <div class="col-4">
                        <input type="submit" value="Login" class="button" id="button">
                    </div>
                    <div class="col-4">
                        <p>Do you have and account? <a href="{% url "users:register" %}" class="btn">create an account</a></p> 
                        <a class="nav_link" href="#">forgot password?</a>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <h3><span style="color:red;">F</span>ind <span style="color:green;">Y</span>our <span style="color:blue">O</span>wn <span style="color:yellow;">W</span>ay</h3>
        </div>
    </div>
{% endblock content %}

templates/users/register.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="row">
            <h3>Start your journey here</h3> 
        </div>
        <div clas="row">
            <form action="" method="post">
                {% csrf_token %}
                <div class="row">
                    <div clas="row">
                        <div class="col-4">
                            {{ form.as_div }}
                        </div>
                        <div class="col-4">
                            <input type="submit" class="button" value="Register" />
                        </div>
                        <div class="col-4">
                            <p>Already have and account? <a href="{% url "users:home" %}" class="btn"/>Login</a></p>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

templates/users/user/dashboard.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome {{username}}</h1>
<a href="{% url "users:home" %}" class="btn">Logout</a>
{% endblock content %}